### ISSUE TITLE
Error from the BadWordSetup system

### ISSUE THREAD

**Issue by master3395** [DanTheComputerMan/javascript#13]
I get this random error from the bot.
Not sure what command in the Bad Word system, is causing this.
This started happening when I added the V2.

```
SyntaxError: Unexpected identifier
    at Object.Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:15)
    at Object.action [as Run Script] (/home/dashboard.newstargeted.com/public_html/nt/actions/run_script.js:132:23)
    at Object.Actions.invokeActions (/home/dashboard.newstargeted.com/public_html/nt/bot.js:502:18)
    at Object.Actions.preformActions (/home/dashboard.newstargeted.com/public_html/nt/bot.js:391:8)
    at Object.Bot.onAnyMessage (/home/dashboard.newstargeted.com/public_html/nt/bot.js:209:13)
    at Object.Bot.onMessage (/home/dashboard.newstargeted.com/public_html/nt/bot.js:166:10)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/home/dashboard.newstargeted.com/public_html/nt/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/dashboard.newstargeted.com/public_html/nt/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/dashboard.newstargeted.com/public_html/nt/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
```

**Comment by master3395** [comment]
Seems to mainly lay in the "Any Message" command. "BadWordFilter"

**Comment by DanTheComputerMan** [comment]
Identified the issue and corrected it.
