### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by master3395** [DanTheComputerMan/javascript#14]
Possible bug when adding words?

`SyntaxError: Invalid regular expression: /\bsu)ck\b/: Unmatched ')'`

```
(node:13145) UnhandledPromiseRejectionWarning: Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
    at /home/dashboard.newstargeted.com/public_html/nt/node_modules/discord.js/src/managers/GuildMemberManager.js:314:16
    at Timeout._onTimeout (/home/dashboard.newstargeted.com/public_html/nt/node_modules/discord.js/src/client/BaseClient.js:83:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:13145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 220)
(node:13145) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /\bsu)ck\b/: Unmatched ')'
    at new RegExp (<anonymous>)
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:107:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 221)
```

**Comment by DanTheComputerMan** [comment]
The "(node:13145) UnhandledPromiseRejectionWarning: Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time." message is not the fault of the system and is either an internet connection issue and/or a bot intents issue.

I'm not sure where exactly the regular expression issue came from, but it would be due to the symbols not being escaped properly. This may be b/c the system has not escaped them properly or may not be; I can look into that.

**Comment by DanTheComputerMan** [comment]
Alright, I did not find issues with is escaping characters. If you're using it as regex which it seems like you're doing, you need to escape certain regex characters. Try placing a \ before the right parenthesis and see if you still experience this issue. If you do, one more thing to try is two \ symbols in a row before the right parenthesis Ex: \\\\)
If you still have an issue with it after that, reply back.

**Comment by master3395** [comment]
Seems like it's not from my server, but some other person's server.
Every time someone says "111fuck1111" instead of "fuck", it prints the error below.

```
(node:13145) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /\bsu)ck\b/: Unmatched ')'
    at new RegExp (<anonymous>)
    at eval (eval at Actions.eval (/home/dashboard.newstargeted.com/public_html/nt/bot.js:344:10), <anonymous>:107:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:13145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1766)
```
